swagger: '2.0'
info:
  description: Learning Application Events
  version: 1.0.0
  title: Learning Application Events
  # put the contact info for your development or API team
  contact:
    email: clifton@infinitaslearning.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: events
  description: Operations related to event retrieval
- name: webhooks
  description: Operations related to webhook management

paths:
  /api/webhook:
    get:
      tags:
      - webhooks
      summary: retrieves list of webhooks registered
      operationId: listWebhooks
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/webhooks'
    post:
      tags:
      - webhooks
      summary: creates or updates a webhook
      operationId: createUpdateWebhook
      produces:
      - application/json
      parameters:
        - in: body
          name: webhook
          schema:
            $ref: '#/definitions/webhook'
      responses:
        '200':
          description: OK
  /api/webhook/{webhookId}:
    get:
      tags:
      - webhooks
      summary: retrieves specific of webhook
      operationId: getWebhook
      produces:
      - application/json
      parameters:
        - in: path
          required: true
          name: webhookId
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/webhook'

    delete:
      tags:
      - webhooks
      summary: deletes a webhook
      operationId: deleteWebhook
      parameters:
        - in: path
          required: true
          name: webhookId
          type: string
      produces:
      - application/json
      responses:
        '200':
          description: OK

  /api/events:
    get:
      tags:
      - events
      summary: retrieves list of events
      operationId: listEvents
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/events'

definitions:
  webhooks:        # <---- dictionary
      type: array
      items:
        type: object
        additionalProperties:
          $ref: '#/definitions/webhook'
  webhook:
    type: object
    required:
    - id
    - url
    - enabled_events
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      url:
        type: string
        example: http://lms.nl/api/webhook
      enabled_events:
        type: array
        items:
          type: string
        example: ["la:usage", "la:results"]
  events:
      type: array
      items:
        type: object
        additionalProperties:
          $ref: '#/definitions/event'
  event:
    type: object
    required:
    - id
    - type
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      type:
        type: string
        example: la:usage

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Infinitas-Learning/sem-learning-application-events/1.0.0
schemes:
 - https
