swagger: '2.0'
host: example.stichtingsem.org
basePath: /sem-api
schemes:
  - https
info:
  version: 1.0.0
  title: API Definition for Event API
  description: |-
    The proposed architecture for the new ecosystem is based on an Event model, where each provider of data to the ecosystem provides a mechanism for other participants to securely subscribe to events that are of interest to them.

        
    The Event API is the mechanism, in conjunction with the Webhook API, that enables this event based notification mechanism to function reliably.  It enables subscribers to request events from the provider, and paginate through to the last place that it received a message.

    Notes:
      - Pagination is essential.
      - Limits should be imposed on page size.
      - Providers should ensure that this API is cacheable or able to be retrieved at minimal cost, as it may be accessed a lot by consumers who are 'catching up'
  contact:
    email: clifton@infinitaslearning.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: events
    description: Operations related to event retrieval
paths:
  /events:
    get:
      description: Allows a subscriber to retrieve a list of past events.
      tags:
        - events
      operationId: listEvents
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/events'
definitions:
  events:
    type: array
    items:
      type: object
      additionalProperties:
        $ref: '#/definitions/event'
  event:
    type: object
    required:
      - id
      - type
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      type:
        type: string
        example: 'la:usage'
securityDefinitions:
  API Key - 1:
    type: oauth2
    flow: application
    scopes: {}
