openapi: '3.0.0'
info:
  version: 1.0.0
  title: Generic Event Stream API
  description: Generic SEM Event Api
  contact:
    email: clifton@infinitaslearning.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: events
    description: Operations related to event retrieval
paths:
  /events:
    get:
      description: Allows a subscriber to retrieve a list of past events.
      tags:
        - events
      operationId: listEvents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events'
components:
  schemas:
    events:
      type: array
      items:
        type: object
        additionalProperties:
          $ref: '#/components/schemas/event'
    event:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        type:
          type: string
          example: 'la:usage'
