openapi: '3.0.0'
host: stichtingsem.nl
basePath: /sem-api
schemes:
 - https
info:
  description: Generic SEM Webhook definition for managing subscriptions.
  version: 1.0.0
  title: Generic Web Hook API

  # put the contact info for your development or API team
  contact:
    email: clifton@infinitaslearning.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

# tags are used for organizing operations
tags:
- name: webhooks
  description: Operations related to webhook management

paths:
  /webhook:
    get:
      tags:
      - webhooks
      description: retrieves list of webhooks registered
      operationId: listWebhooks
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/webhooks'
    post:
      tags:
      - webhooks
      description: creates or updates a webhook
      operationId: createUpdateWebhook
      produces:
      - application/json
      parameters:
        - in: body
          name: webhook
          schema:
            $ref: '#/definitions/webhook'
      responses:
        '200':
          description: OK
  /webhook/{webhookId}:
    get:
      tags:
      - webhooks
      description: retrieves specific of webhook
      operationId: getWebhook
      produces:
      - application/json
      parameters:
        - in: path
          required: true
          name: webhookId
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/webhook'

    delete:
      tags:
      - webhooks
      description: deletes a webhook
      operationId: deleteWebhook
      parameters:
        - in: path
          required: true
          name: webhookId
          type: string
      produces:
      - application/json
      responses:
        '200':
          description: OK

definitions:
  webhooks:
      type: array
      items:
        type: object
        additionalProperties:
          $ref: '#/definitions/webhook'
  webhook:
    type: object
    required:
    - id
    - url
    - enabled_events
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      url:
        type: string
        description: The url that will be called when any of the subscribed events occur
        example: http://lms.nl/api/webhook
      enabled_events:
        type: array
        description: Allow filtering of events that should be sent to this endpoint
        items:
          type: string
        example: ["la:usage", "la:results"]
