/*
 * Provider Catalogue API
 *
 * This API enables a learning application provider (or anyone who wants to sell products in a Marketplace) to provide information about their products to a Marketplace.  It is envisaged that the service implementing this API, also implements the generic [Events](https://stichtingsem.stoplight.io/docs/sem-technology-prototype/reference/events.v1.yaml) and [Webhooks](https://stichtingsem.stoplight.io/docs/sem-technology-prototype/reference/webhooks.v1.yaml) API to enable subscription to changes vs polling.  ## Scopes and Data  It is envisaged that when a connection is made between a Marketplace and a Learning Application, that the API Key then provided is connected to that specific marketplace.   This connection ensures that the Learning Application can provide information that may be specific to commercial agreements with a specific marketplace (e.g. pricing information).  This specification provides the placeholders for this information to be exchanged, but has no restriction on what is agreed between parties offline.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
   /// <summary>
   /// The combination of level and subject that indicates what a product is targeted at.
   /// </summary>
   [DataContract]
   public partial class LevelSubjects : IEquatable<LevelSubjects>
   {
      /// <summary>
      /// Government level - e.g. havo-1
      /// </summary>
      /// <value>Government level - e.g. havo-1</value>
      [DataMember(Name = "level")]
      public string Level { get; set; }

      /// <summary>
      /// Subject code for specific subject at this level 
      /// </summary>
      /// <value>Subject code for specific subject at this level </value>
      [DataMember(Name = "subjectCode")]
      public string SubjectCode { get; set; }

      /// <summary>
      /// Returns the string presentation of the object
      /// </summary>
      /// <returns>String presentation of the object</returns>
      public override string ToString()
      {
         var sb = new StringBuilder();
         sb.Append("class LevelSubjects {\n");
         sb.Append("  Level: ").Append(Level).Append("\n");
         sb.Append("  SubjectCode: ").Append(SubjectCode).Append("\n");
         sb.Append("}\n");
         return sb.ToString();
      }

      /// <summary>
      /// Returns the JSON string presentation of the object
      /// </summary>
      /// <returns>JSON string presentation of the object</returns>
      public string ToJson()
      {
         return JsonConvert.SerializeObject(this, Formatting.Indented);
      }

      /// <summary>
      /// Returns true if objects are equal
      /// </summary>
      /// <param name="obj">Object to be compared</param>
      /// <returns>Boolean</returns>
      public override bool Equals(object obj)
      {
         if (ReferenceEquals(null, obj)) return false;
         if (ReferenceEquals(this, obj)) return true;
         return obj.GetType() == GetType() && Equals((LevelSubjects)obj);
      }

      /// <summary>
      /// Returns true if LevelSubjects instances are equal
      /// </summary>
      /// <param name="other">Instance of LevelSubjects to be compared</param>
      /// <returns>Boolean</returns>
      public bool Equals(LevelSubjects other)
      {
         if (ReferenceEquals(null, other)) return false;
         if (ReferenceEquals(this, other)) return true;

         return
             (
                 Level == other.Level ||
                 Level != null &&
                 Level.Equals(other.Level)
             ) &&
             (
                 SubjectCode == other.SubjectCode ||
                 SubjectCode != null &&
                 SubjectCode.Equals(other.SubjectCode)
             );
      }

      /// <summary>
      /// Gets the hash code
      /// </summary>
      /// <returns>Hash code</returns>
      public override int GetHashCode()
      {
         unchecked // Overflow is fine, just wrap
         {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (Level != null)
               hashCode = hashCode * 59 + Level.GetHashCode();
            if (SubjectCode != null)
               hashCode = hashCode * 59 + SubjectCode.GetHashCode();
            return hashCode;
         }
      }

      #region Operators
#pragma warning disable 1591

      public static bool operator ==(LevelSubjects left, LevelSubjects right)
      {
         return Equals(left, right);
      }

      public static bool operator !=(LevelSubjects left, LevelSubjects right)
      {
         return !Equals(left, right);
      }

#pragma warning restore 1591
      #endregion Operators
   }
}
