/*
 * Provider Catalogue API
 *
 * This API enables a learning application provider (or anyone who wants to sell products in a Marketplace) to provide information about their products to a Marketplace.  It is envisaged that the service implementing this API, also implements the generic [Events](https://stichtingsem.stoplight.io/docs/sem-technology-prototype/reference/events.v1.yaml) and [Webhooks](https://stichtingsem.stoplight.io/docs/sem-technology-prototype/reference/webhooks.v1.yaml) API to enable subscription to changes vs polling.  ## Scopes and Data  It is envisaged that when a connection is made between a Marketplace and a Learning Application, that the API Key then provided is connected to that specific marketplace.   This connection ensures that the Learning Application can provide information that may be specific to commercial agreements with a specific marketplace (e.g. pricing information).  This specification provides the placeholders for this information to be exchanged, but has no restriction on what is agreed between parties offline.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
   /// <summary>
   /// A reference to a video, image or document that can be used by a Marketplace (or LMS).
   /// </summary>
   [DataContract]
   public partial class Media : IEquatable<Media>
   {
      /// <summary>
      /// Gets or Sets Url
      /// </summary>
      [DataMember(Name = "url")]
      public string Url { get; set; }

      /// <summary>
      /// Gets or Sets Type
      /// </summary>
      [DataMember(Name = "type")]
      public string Type { get; set; }

      /// <summary>
      /// Gets or Sets Description
      /// </summary>
      [DataMember(Name = "description")]
      public string Description { get; set; }

      /// <summary>
      /// Gets or Sets Width
      /// </summary>
      [DataMember(Name = "width")]
      public string Width { get; set; }

      /// <summary>
      /// Gets or Sets Height
      /// </summary>
      [DataMember(Name = "height")]
      public string Height { get; set; }

      /// <summary>
      /// Returns the string presentation of the object
      /// </summary>
      /// <returns>String presentation of the object</returns>
      public override string ToString()
      {
         var sb = new StringBuilder();
         sb.Append("class Media {\n");
         sb.Append("  Url: ").Append(Url).Append("\n");
         sb.Append("  Type: ").Append(Type).Append("\n");
         sb.Append("  Description: ").Append(Description).Append("\n");
         sb.Append("  Width: ").Append(Width).Append("\n");
         sb.Append("  Height: ").Append(Height).Append("\n");
         sb.Append("}\n");
         return sb.ToString();
      }

      /// <summary>
      /// Returns the JSON string presentation of the object
      /// </summary>
      /// <returns>JSON string presentation of the object</returns>
      public string ToJson()
      {
         return JsonConvert.SerializeObject(this, Formatting.Indented);
      }

      /// <summary>
      /// Returns true if objects are equal
      /// </summary>
      /// <param name="obj">Object to be compared</param>
      /// <returns>Boolean</returns>
      public override bool Equals(object obj)
      {
         if (ReferenceEquals(null, obj)) return false;
         if (ReferenceEquals(this, obj)) return true;
         return obj.GetType() == GetType() && Equals((Media)obj);
      }

      /// <summary>
      /// Returns true if Media instances are equal
      /// </summary>
      /// <param name="other">Instance of Media to be compared</param>
      /// <returns>Boolean</returns>
      public bool Equals(Media other)
      {
         if (ReferenceEquals(null, other)) return false;
         if (ReferenceEquals(this, other)) return true;

         return
             (
                 Url == other.Url ||
                 Url != null &&
                 Url.Equals(other.Url)
             ) &&
             (
                 Type == other.Type ||
                 Type != null &&
                 Type.Equals(other.Type)
             ) &&
             (
                 Description == other.Description ||
                 Description != null &&
                 Description.Equals(other.Description)
             ) &&
             (
                 Width == other.Width ||
                 Width != null &&
                 Width.Equals(other.Width)
             ) &&
             (
                 Height == other.Height ||
                 Height != null &&
                 Height.Equals(other.Height)
             );
      }

      /// <summary>
      /// Gets the hash code
      /// </summary>
      /// <returns>Hash code</returns>
      public override int GetHashCode()
      {
         unchecked // Overflow is fine, just wrap
         {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (Url != null)
               hashCode = hashCode * 59 + Url.GetHashCode();
            if (Type != null)
               hashCode = hashCode * 59 + Type.GetHashCode();
            if (Description != null)
               hashCode = hashCode * 59 + Description.GetHashCode();
            if (Width != null)
               hashCode = hashCode * 59 + Width.GetHashCode();
            if (Height != null)
               hashCode = hashCode * 59 + Height.GetHashCode();
            return hashCode;
         }
      }

      #region Operators
#pragma warning disable 1591

      public static bool operator ==(Media left, Media right)
      {
         return Equals(left, right);
      }

      public static bool operator !=(Media left, Media right)
      {
         return !Equals(left, right);
      }

#pragma warning restore 1591
      #endregion Operators
   }
}
