name: Publish Documentation to Bump.sh

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: API documentation on Bump
      uses: bump-sh/github-action@0.1
      with:
        # Relative path to the documentation file
        file: reference/events.v1.yaml
        id: 069326d2-5dcb-4a5e-afe6-a25681658d8c
        token: 1ead9c529cb2ae440e3997c3a321d6dd
        validation: basic
